services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: jinshiagencysbyte/examen-laravel:latest
    container_name: examen-laravel-app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8000:80"
      - "443:443"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: base64:QX5Wk0B0vZ2lP5w7d3h5Q1nM3YQF3sLkzZcFaPj7X7Q=
      APP_URL: http://localhost:8000
      LOG_CHANNEL: stack
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: examen_laravel
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
      SESSION_DRIVER: file
      CACHE_STORE: file
      QUEUE_CONNECTION: sync
    volumes:
      - .:/var/www/html:cached
      - app_storage:/var/www/html/storage
      - app_cache:/var/www/html/bootstrap/cache
      - app_config:/etc/inventory-booking-system/config
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: examen-laravel-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: examen_laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
  app_storage:
  app_cache:
  app_config:
